name: Test SSH Connection

on:
  workflow_dispatch:  # Enables a manual run button in the Actions tab

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          printf '%s\n' "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Test SSH connection
        env:
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          echo "Testing SSH connection to $USERNAME@$HOST..."
          ssh -v -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST "echo '✅ Connected successfully!'"
