name: Deploy To Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Deploy to Server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Stop existing process if running
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            mkdir -p /home/$USERNAME/app
            pkill -f "python3 madlibs.py" || true
          EOF

          # Copy all project files to the server
          scp -i private_key.pem -o StrictHostKeyChecking=no -r ./* $USERNAME@$HOST:/home/$USERNAME/app

          # Install dependencies and restart the app
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            cd /home/$USERNAME/app
            python3 -m pip install flask
            nohup python3 madlibs.py >> app.log 2>&1 &
            disown
          EOF
